fix Dataset importer problems
mozilla/translations pull request #342
Opened 2024-01-09 05:21 UTC by AmitMY

fix #338

2024-01-09 21:08 UTC, gregtatum approved these changes
Thanks, looks good to me.

2024-01-09 21:09 UTC, gregtatum commented
Oh wait, the tests aren't passing. We should investigate that before merging.

2024-01-11 14:10 UTC, gregtatum requested changes
It looks like this is causing real test failures. I'm requesting changes since I believe this is breaking things.

`sacreBLEU: Unknown test set 'aug-mix_wmt19'`

2024-01-11 21:04 UTC, AmitMY commented
Seems like `_` is a word character (`\w`), let's try with it optional.  We'll see if there's another issue in the tests

2024-01-12 20:41 UTC, gregtatum approved these changes
CI looks good! Let's wait until #362 merges, then I can rebase and merge. Thanks for the fix.

2024-01-29 20:13 UTC, gregtatum requested changes
It looks like CI is still failing here.

2024-01-30 08:39 UTC, AmitMY commented
It did pass before you merged master again, iirc

2024-01-30 14:25 UTC, gregtatum commented
There is a red X next to your previous pushes, see: https://github.com/mozilla/firefox-translations-training/runs/20456494808

That looks like an intermittent failure, but it never got to the eval steps.

2025-04-03 16:37 UTC, marco-c commented
@AmitMY are you still using the pipeline?

2025-04-03 17:57 UTC, AmitMY commented
> @AmitMY are you still using the pipeline?

no

2025-04-03 18:00 UTC, closed without merging